encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:titleinp>",views.content,name="content"),
    path("customlanguage",views.custom,name="custom"),
    path("addoredit",views.edit,name="edit"),
    path("delete",views.delete,name="delete")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from . import util
import markdown2
from django.core.files import File
import os

def index(request):
    editcheck = False
    listentries = False
    customcheck = False
    if request.method == "POST":     
        return util.searchfunction(util.Newsearch(request.POST),request)
    else:
        listentries = True
        return render(request, "encyclopedia/index.html", {"editcheck":editcheck,"customcheck":customcheck,"entries": util.list_entries(),"listcheck": listentries,"searchcont": util.Newsearch()})

def content(request,titleinp):
    editcheck = False
    listentries = False
    customcheck = False
    textshow = True
    return render(request,"encyclopedia/index.html",{"textshow":textshow,"editcheck":editcheck,"customcheck":customcheck,"titleurl":titleinp,"fulltxt": markdown2.markdown(util.get_entry(titleinp)),"listcheck": listentries,"searchcont": util.Newsearch()})

def custom(request):
    editcheck = False
    listentries = False
    customcheck = True
    dataini = "####Text to htm from scratch for challenge CS50w\n#h1\n######h6\nA New Paragraph Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text\n\n\n*itallic* **bold** ***both*** [Link:to Home](/) Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text\n\n-list1\n-list2"
    if request.method == "POST":
        return util.customfunction(util.cfunc(dataini)(request.POST),request)
    else:
        return render(request, "encyclopedia/index.html", {"fulltxt":util.to_htm(dataini),"editcheck":editcheck,"customcheck":customcheck,"listcheck": listentries,"customapp": util.cfunc(dataini),"searchcont": util.Newsearch()})

def edit(request):
    titleini="Title"
    dataini="Use Markdown2 Format"
    pathvar = request.META.get('HTTP_REFERER')
    if pathvar == None:
        pathvar = "addoredit"
    else:
        pathvar = util.removeextrapath(pathvar)
    customcheck = False
    listentries = False
    editcheck = True
    existingitem = False
    for item in util.list_entries():
        if str.lower(pathvar) == str.lower(item):
            existingitem = True
    if request.method == "POST":
        tit = util.tfunc(titleini)(request.POST)
        cont = util.dfunc(dataini)(request.POST)
        if cont.is_valid():
            datainp = cont.cleaned_data["editapp"] 
        if tit.is_valid():
            titleinp =  tit.cleaned_data["titleapp"]
                  
        #add new post
        righthead = f"Add New Entry"
        with open(f'entries/{titleinp}.md','w') as f:
            currentfile = File(f)
            currentfile.write(datainp)
        
        return redirect(f'/wiki/{titleinp}')

    else:
        #modify existing get
        if existingitem:
            titleini = pathvar
            dataini = util.get_entry(pathvar)
            righthead = f"Edit Entry for <strong>{str.upper(pathvar)}</strong>"
            return render(request, "encyclopedia/index.html", {"righthead":righthead,"editcheck":editcheck,"fulltxt":f"getmod:{pathvar}","customcheck":customcheck,"listcheck": listentries,"editapp": util.dfunc(dataini),"searchcont": util.Newsearch(),"title": util.tfunc(titleini)})
        #add new get
        else:
            righthead = f"Add new entry"
            return render(request, "encyclopedia/index.html", {"righthead":righthead,"editcheck":editcheck,"fulltxt":f"getadd:{pathvar}","customcheck":customcheck,"listcheck": listentries,"editapp": util.dfunc(dataini),"searchcont": util.Newsearch(),"title": util.tfunc(titleini)})

def delete(request):
    pathvar = request.META.get('HTTP_REFERER')
    if pathvar == None:
        pathvar = ""
    else:
        pathvar = util.removeextrapath(pathvar)
    
    customcheck = False
    listentries = False
    editcheck = False
    existingitem = False
    deletecheck = True

    for item in util.list_entries():
        if str.lower(pathvar) == str.lower(item):
            existingitem = True
    
    suretxt = f"Are you sure you want to <strong>delete: {pathvar}</strong>?"
    
    if request.method != "POST":#get
        with open('pathstore.md','w') as f:
            currentfile = File(f)
            currentfile.write(pathvar)
        return render(request, "encyclopedia/index.html", {"deletecheck":deletecheck,"suretxt":suretxt,"editcheck":editcheck,"fulltxt":"Are You Sure?","customcheck":customcheck,"listcheck": listentries,"searchcont": util.Newsearch()})
    else:
        with open('pathstore.md','r') as f:
            currentfile = File(f)
            previous_path = currentfile.read()
        os.remove(f'entries/{previous_path}.md')        
        return redirect(f'/')

                
    
        

    

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{% if listcheck %}
Encyclopedia
{% else %}
{{titleurl}}
{% endif %}
{% endblock %}

{% block sidebar %}
{% if textshow %}
    <a href="/delete">
        <div class="lhomebutton">
            Delete Entry
        </div>
    </a>
    {% endif %}
{% endblock %}


{% block body %}

    {% if deletecheck %}
        <div class="tocent">
            {{suretxt|safe}}<br>
            <a href ="/">
                <div class="no">
                    No
                </div>
            </a>
            <br>
            <form action="{% url 'homepage:delete' %}" method="POST">
                {% csrf_token %}
                {{delapp}}
                <input type="submit" value="Yes">
            </form>
            <br>
        </div>
        
    {% endif %}

    {% if listcheck %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}" style = "color:black" >{{entry}}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if customcheck %}
    <form action="{% url 'homepage:custom' %}" method="POST">
        {% csrf_token %}
        {{ customapp }}
        <br>
        <div class = "preview"><input type="submit" value="Preview"></div>
    </form>
    {{fulltxt|safe}}
    {% endif %}
    {% if editcheck %}
    {{righthead|safe}}    
    <form action="{% url 'homepage:edit' %}" method="POST">
        {% csrf_token %}
        Title :
        {{title}}
        {{ editapp }}
        <br>
        <input type="submit" value="Save Changes">
    </form>
    {% endif %}
    
    {% if textshow %}
    {{fulltxt|safe}}
    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}">
        <link rel='icon' href="{% static 'encyclopedia/favico.png' %}" type='image/x-icon'/ >
        <meta name="viewport" content="width=device-width", initial-scale=1.0">  
        <style>
        .pagebg{
            position: fixed;
            background-image: url({% static 'encyclopedia/bg.jpg' %});
            background-size: cover;
            height: 100vh;
            width: 100vw;
            top: 0; right: 0; bottom: 0; left: 0;
            z-index: -1;
            overflow-x: hidden;
          }
        </style>
        </head>
    <body>
        <div class=pagebg></div>
        <div class=topbar>
            <div class="searchbar topsearchbar">
                <div class="topbutton">
                    <a href="/"><div class="homebutton"><img src="{% static 'encyclopedia/homeicon.png' %}" width="30px">      HOME</div></a>
                </div>             
                <form action="{% url 'homepage:index' %}" method="POST">
                    {% csrf_token %}
                    {{ searchcont }}
                    <input type="submit" value="SEARCH">
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-xl-3 d-none d-lg-block leftcolm">
                <a href="/">
                    <div class="lhomebutton">
                        <img src="{% static 'encyclopedia/homeicon.png' %}" width="30px">&nbsp; Wiki Home
                    </div>
                </a>
                <div class="headings">Search Our Wiki</div> 
                <div class="searchbar">                 
                    <form action="{% url 'homepage:index' %}" method="POST">
                        {% csrf_token %}
                        {{ searchcont }}<br>
                        <input type="submit" value="SEARCH">
                    </form>
                </div> 
                <a href="/addoredit">
                    <div class="lhomebutton">
                        Add/Modify Entries
                    </div>
                </a>
                {%block sidebar %}         
                {%endblock%}
                <a href="/customlanguage">
                    <div class="lhomebutton">
                        Custom MD language
                    </div>
                </a>       
            </div>
            <div class="col-lg-1 col-xl-1 d-none d-lg-block">
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-7 col-xl-7 rightcolm">
                {% block body %}
                {% endblock %}    
            </div>
            <div class="col-lg-1 col-xl-1 d-none d-lg-block">
            </div>
    </body>
</html>